# Generated by Django 4.1 on 2025-05-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('model', 'manufacturer')},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ('first_name',)},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ('name',)},
        ),
    ]
