# Generated by Django 4.1 on 2025-05-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_car_options_alter_driver_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('manufacturer',)},
        ),
    ]
