# Generated by Django 4.1 on 2025-05-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('manufacturer', 'model')},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ('first_name', 'last_name')},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ('name', 'country')},
        ),
    ]
